### ISSUE TITLE
Error in get.psid(psidFiles[i, "file"], name = paste0(datadir, "FAM",  : no longer logged in

### ISSUE THREAD

**Issue by hack-r** [floswald/psidR#11]
I apologize in advance if this is a very ignorant problem generated by user error, but I can't seem to get the data pull from the Data Center to work.

Every time I run the example query with my login email and password, it fails with an error saying `    Error in get.psid(psidFiles[i, "file"], name = paste0(datadir, "FAM",  : no longer logged in`. This persists across computers. 

I'm presuming that username is the email address used to login to the PSID Data Center, because I did not see any other username. I tried it with and without quotation marks.

    > d <- build.panel(datadir=my.dir,fam.vars=famvars,
    + ind.vars=indvars, SAScii = T,
    + heads.only=FALSE,verbose=TRUE)
    This can take several hours/days to download.
     want to go ahead? give me 'yes' or 'no'.yes
    please enter your PSID username: username@gmail.com
    please enter your PSID password: mypass
    Error in get.psid(psidFiles[i, "file"], name = paste0(datadir, "FAM",  : 
      no longer logged in
    > my.dir <- tempdir()
    > d <- build.panel(datadir=my.dir,fam.vars=famvars,
    +                  ind.vars=indvars, SAScii = T,
    +                  heads.only=FALSE,verbose=TRUE)
    This can take several hours/days to download.
     want to go ahead? give me 'yes' or 'no'.yes
    please enter your PSID username: "username@gmail.com"
    please enter your PSID password: "mypass"
    Error in get.psid(psidFiles[i, "file"], name = paste0(datadir, "FAM",  : 
      no longer logged in

**Comment by floswald** [comment]
good catch - doesn't work for me either. This is likely to be an upstream issue with SAScii, I'll try to investigate.

**Comment by hack-r** [comment]
Awesome, thank you!

**Comment by floswald** [comment]
fixed in f2bc2b4d1eb7245bf09a1757a9b0e20e2ce82f13
