### ISSUE TITLE
update to psid in 2013

### ISSUE THREAD

**Issue by jonlatner** [floswald/psidR#12]
floswald,

thanks for putting this package together!  out of curiosity, when do you plan to update the code to allow for psid through 2013?  alternatively, could you suggest how to adapt the code directly?  when i used psiduse in stata, there was always some lag between when the new data was available and the code was updated.  this wasn't a problem as i just updated the code directly for myself in the .ado file.  however, i am new to R and do not know how to do that.

thanks,

JPL

**Comment by floswald** [comment]
hey, sorry for the delay , i missed that. fixed in c931748470d5644764f756c189b48b0f47d32a68
