### ISSUE TITLE
problems downloading data/replicating example

### ISSUE THREAD

**Issue by lguirola** [floswald/psidR#15]
Hi,

I am trying to familiarize myself with psidr to build my own dataset. For now, I am just trying to replicate the example in the readme.txt document.

After creating `fam` and `ind` data.tables apparently identical to the example, I get an error when I try to run

```
dir = getwd()
d = build.panel(datadir=dir,
                fam.vars=fam,
                ind.vars=ind,
               SAScii = TRUE, 
              heads.only = TRUE,
              sample="SRC",
              design=2)
```

my output is

```
downloading file  /Users/luisguirola/Box Sync/ISdynamics/data/FAMNAER 
error 1 in extracting from zip filenow reading and processing SAS file /Users/luisguirola/Box Sync/ISdynamics/data/FAMNAER into R
Error in file(con, "r") : invalid 'description' argument
```

Following our email exchange, I have also tried:

`dd = build.panel(dir,fam,verbose=TRUE, SAScii = TRUE)`

getting

```
downloading file  /Users/luisguirola/Box Sync/ISdynamics/data/FAMNAER 
error 1 in extracting from zip filenow reading and processing SAS file /Users/luisguirola/Box Sync/ISdynamics/data/FAMNAER into R
Error in file(con, "r") : invalid 'description' argument
```

If I drop the `SAScii = TRUE` argument, as you suggested:

```
I'm setting your encoding to windows nowError in build.panel(dir, fam, verbose = TRUE) : 
  No .dta, .rda, .RData or .csv files found in directory
```

**Comment by floswald** [comment]
Very odd. Do you have a psid user name and did you supply it to the function when it asked you? Also, 'dir' needs to exist.

**Comment by floswald** [comment]
hi there
i pushed a new version. do you want to try out as explained in this issue #16 ?
let me know if it works.
