### ISSUE TITLE
problem with datadir

### ISSUE THREAD

**Issue by clizama** [floswald/psidR#22]
I'm trying to use build.panel. I tried providing the Family Files in the Form FAMyyy.xyz. I tried many formats, csv, Stata, dta, RData, and it does nos work with any of them.

For the csv files, I get this error:
"Error in fread(input = ind.file) : 
  File 'FamFiles/CSV/' is a directory. Not yet implemented."

For stata files, I get this one:
"Error in read.dta(file = ind.file) : a binary read error occurred"

Similar errors found for dta and RData files.

Any idea about what might be going on?

**Comment by floswald** [comment]
Hi there

Will need a bit more info. Can you post the full code of your use case
please? I have not tested the stata build option in quite a while, so maybe
an old stata format is breaking this. I do now recommend the SAScii option
to download directly from psid.

**Comment by clizama** [comment]
Sure, this is the full code....

library("psidR")
library("openxlsx")
library("tidyverse")
library("foreign") # to read Stata files properly 

setwd("/Users/carloslizama/Desktop/Data/R")

# get variable names (codes for year 2015) ================
codes = c("ER60002", # family id number
          "ER60009", # family number, 1968.
          "ER65200", # wages and salaries of head
          "ER65216", # Labor income of head
          "ER65156", # head's total hours
          "ER60017" # age of head of the family
          )
N_var = length(codes)

# READ EXCEL SPREADSHEET
cwf <- read.xlsx("psid.xlsx",1)
cpi <- read.xlsx("cpi.xlsx",1)
years = cpi$year

# OBTAIN CODES
#id <- getNamesPSID(codes[1],cwf,years) # family id current year
#id68 <- getNamesPSID(codes[2],cwf,years) # family id 1968
wages <- as.vector(t(getNamesPSID(codes[3],cwf,years))) # wages and salaries
labor_income <- as.vector(t(getNamesPSID(codes[4],cwf, years))) # labor income
hours <- as.vector(t(getNamesPSID(codes[5], cwf, years)))  # hours per week, head.
age <- as.vector(t(getNamesPSID(codes[6], cwf, years))) # age

famvars <- data.frame(years,wages,labor_income,hours,age)

# BUILD PANEL (WITH HOUSEHOLD HEADS)
build.panel(datadir = "FamFiles/STATA", 
            fam.vars = famvars, ind.vars = NULL,
            wealth.vars = NULL, SAScii = FALSE, heads.only = TRUE, 
            current.heads.only = FALSE,
            sample = NULL, design = 5, verbose = FALSE)

I will try the SAScii option. 

Thank you.

**Comment by floswald** [comment]
can you show me `list.files("FamFiles/STATA")` please?

**Comment by clizama** [comment]
This is the output of list.files("FamFiles/STATA")

[1] "FAM1969.dta" "FAM1970.dta" "FAM1971.dta" "FAM1972.dta" "FAM1973.dta"
 [6] "FAM1974.dta" "FAM1975.dta" "FAM1976.dta" "FAM1977.dta" "FAM1978.dta"
[11] "FAM1979.dta" "FAM1980.dta" "FAM1981.dta" "FAM1982.dta" "FAM1983.dta"
[16] "FAM1984.dta" "FAM1985.dta" "FAM1986.dta" "FAM1987.dta" "FAM1988.dta"
[21] "FAM1989.dta" "FAM1990.dta" "FAM1991.dta" "FAM1992.dta" "FAM1993.dta"
[26] "FAM1994.dta" "FAM1995.dta" "FAM1996.dta" "FAM1997.dta" "FAM1999.dta"
[31] "FAM2001.dta" "FAM2003.dta" "FAM2005.dta" "FAM2007.dta" "FAM2009.dta"
[36] "FAM2011.dta" "FAM2013.dta" "FAM2015.dta"

I just realized that when I run the code with the SAScii option, the files are generated with ER after the year, for instance I have the file FAM1980ER.dta.

Do you think the reason why my code does not work is because my "FAMyyyy" files do not contain the ER ??

**Comment by floswald** [comment]
I think that’s fine. But you miss the individual index file. That needs to
be placed in the datadir as well.

**Comment by floswald** [comment]
closing this now
