### ISSUE TITLE
unused argument(SAScii=TRUE)

### ISSUE THREAD

**Issue by youngceltic** [floswald/psidR#29]
library(psidR)
library(data.table)
d = build.panel(datadir="~/data",fam.vars=fam,
                ind.vars=ind,
                SAScii = TRUE, 
                heads.only = TRUE,
                sample="SRC",
                design=2)

I get the following error:
Error in build.panel(datadir = "~/data", fam.vars = fam, ind.vars = ind,  : 
  unused argument (SAScii = TRUE)

**Comment by floswald** [comment]
sorry the lower part of the readme is out of date. in case of doubt please consult `?build.panel` for up to date help. i changed the readme example (arg `SAScii` has been removed...)

**Comment by youngceltic** [comment]
Thanks.  I think the program is great.  Very useful.
