### ISSUE TITLE
Error build.panel with NA's in famvars with Data.table 

### ISSUE THREAD

**Issue by SchroederAdrian** [floswald/psidR#32]
Hey guys! 

Just tried to run the build.panel function. It did download all the files successfully and I put them into a separate folder. However, now that I run the function I get an error code : 

Error in `[.data.table`(yind, , `:=`((as.character(ind.nas)), NA)) : 
  Can't assign to the same column twice in the same query (duplicates detected).
In addition: Warning message:
In `[.data.table`(tmp, , `:=`((nanames), NA_real_), with = FALSE) :
  with=FALSE ignored, it isn't needed when using :=. See ?':=' for examples.

Might be my fault of ill-defining my variables? I just use the getNamesPSID function and plug it into a data.table, similar to the example code: 
`
library(psidR)
library(openxlsx)
library(data.table)
cwf <- read.xlsx("http://psidonline.isr.umich.edu/help/xyr/psid.xlsx")

id.ind.educ <- getNamesPSID("ER30010", cwf)
id.ind.transfer <- getNamesPSID("ER30175", cwf)
id.ind.weights <- getNamesPSID("ER30019", cwf)

id.fam.children <- getNamesPSID("V398", cwf)
id.fam.age <- getNamesPSID("V117", cwf)
id.fam.marstat <- getNamesPSID("V239", cwf)
id.fam.sex <- getNamesPSID("V119", cwf)
id.fam.coleduc <- getNamesPSID("V4093", cwf)
id.fam.taxes <- getNamesPSID("V1208", cwf)
id.fam.comp <- getNamesPSID("V542", cwf)
id.fam.disable <- getNamesPSID("V2718", cwf)
id.fam.income <- getNamesPSID("V81", cwf)
id.fam.adc <- getNamesPSID("V80", cwf)
id.fam.weights <- getNamesPSID("V439", cwf)
id.fam.hourlyEarnings <- getNamesPSID("V337", cwf)
id.fam.annualHours <- getNamesPSID("V47", cwf)
id.fam.weeklyHours <- getNamesPSID("V225", cwf)

famvars <- data.table(year=c(1968, 1969, 1970, 1971, 1972, 1973, 1974, 1975, 1976, 1977, 1978, 1979, 1980, 1981, 1982, 1983, 1984, 1985, 1986, 1987, 1988, 1989, 1990, 1991, 1992, 1993, 1994, 1995, 1996, 1997, 1999, 2001, 2003, 2005, 2007, 2009, 2011, 2013, 2015, 2017),
           children=id.fam.children,
           age=id.fam.age,
           marriage=id.fam.marstat,
           sex=id.fam.sex,
           educ=id.fam.coleduc,
           taxes=id.fam.taxes,
           fam.change=id.fam.comp,
           disability=id.fam.disable,
           income=id.fam.income,
           additional.transfer=id.fam.adc,
           fam.weights=id.fam.weights,
           hourly.earnings=id.fam.hourlyEarnings,
           annual.hours=id.fam.annualHours,
           weekly.hours=id.fam.weeklyHours
           )
indvars <- data.table(year=c(1968, 1969, 1970, 1971, 1972, 1973, 1974, 1975, 1976, 1977, 1978, 1979, 1980, 1981, 1982, 1983, 1984, 1985, 1986, 1987, 1988, 1989, 1990, 1991, 1992, 1993, 1994, 1995, 1996, 1997, 1999, 2001, 2003, 2005, 2007, 2009, 2011, 2013, 2015, 2017),
                     school=id.ind.educ,
                     ind.transfer=id.ind.transfer,
                     ind.weights=id.ind.weights
                     )
build.panel(datadir = "/Users/Adrian/Documents/ECON 490/Heteroskedastic Dependency/Dependency/RDA", fam.vars = famvars, ind.vars = indvars, sample = "SRC", design = 3)
`

If you change the directory in the last line to your machine (if you have the data), error should be reproducible.

If it relates to the NA's within each getNames argument, is there a workaround where I still preserve the corresponding year so I can tell that apart in my panel? 

Thanks so much for your help :)

EDIT: here the traceback():

3: `[.data.table`(yind, , `:=`((as.character(ind.nas)), NA))
2: yind[, `:=`((as.character(ind.nas)), NA)]
1: build.panel(datadir = "/Users/Adrian/Documents/ECON 490/Heteroskedastic Dependency/Dependency/RDA", 
       fam.vars = famvars, ind.vars = indvars, sample = "SRC", design = 3)

I've also seen the other issue thread but I only have the RDA files in that directory so that couldn't be the cause... 

EDIT 2: 
Noticed the other issue threads and excluded the Individual files completely, still get the following Errors: 

`
Error in `[.data.table`(ind, , c(def.subsetter, c(ind.subsetter)), with = FALSE) : 
  column(s) not found: NA, NA, NA
In addition: There were 39 warnings (use warnings() to see them)
> traceback()
5: stop("column(s) not found: ", paste(ansvars[is.na(ansvals)], 
       collapse = ", "))
4: `[.data.table`(ind, , c(def.subsetter, c(ind.subsetter)), with = FALSE)
3: ind[, c(def.subsetter, c(ind.subsetter)), with = FALSE]
2: copy(ind[, c(def.subsetter, c(ind.subsetter)), with = FALSE])
1: build.panel(datadir = "/Users/Adrian/Documents/ECON 490/Heteroskedastic Dependency/Dependency/RDA", 
       fam.vars = famvars, ind.vars = NULL, sample = "SRC", design = 3)
`

**Comment by SchroederAdrian** [comment]
Also just checked with Excel, seems like besides the NA's there are no variable duplicates or so...

**Comment by floswald** [comment]
Oh my.... never responded to this! Really sorry. Will check today.

**Comment by floswald** [comment]
tracking this in #34
