### ISSUE TITLE
Install psidR

### ISSUE THREAD

**Issue by ghost** [floswald/psidR#37]
Hell, I run into an installation problem. It seems stupid....
My Rstudio is the latest version.  When I installed using  install.packages("psidR"), the following message popped up: 

trying URL 'https://cran.rstudio.com/bin/macosx/el-capitan/contrib/3.4/psidR_1.9.tgz'
Content type 'application/x-gzip' length 1860375 bytes (1.8 MB)
==================================================
downloaded 1.8 MB

The downloaded binary packages are in
	/var/folders/1b/47gplrds7vqbqf2tq77k1gx00000gp/T//RtmpH2NiIb/downloaded_packages

When I used the following two different options, both seemed not working either.

> install.packages("~/Downloads/psidR_1.9-3.tar", repos = NULL)
Error in install.packages : type == "both" cannot be used with 'repos = NULL'
> install.packages("~/Downloads/psidR_1.9-3.tar", type = "both")
Warning in install.packages :
  package ‘~/Downloads/psidR_1.9-3.tar’ is not available (for R version 3.4.1)

Could you shed light on what the problem might be? Thanks a lot!

**Comment by floswald** [comment]
the first output indicates the package was installed successfully. type `library(psidR)` to check.

**Comment by tobinzt** [comment]
> the first output indicates the package was installed successfully. type `library(psidR)` to check.

Thanks for your reply! It indeed worked after my OS was rebooted.
