### ISSUE TITLE
error

### ISSUE THREAD

**Issue by hyperfra** [floswald/psidR#38]
Dear Florian when I try to run your first example (or others that I build) I am able to download everything but then at the moment of the construction of the panel I get

Error in `[.data.table`(tmp, , codes, with = FALSE) : 
  column(s) not found: <na>

can u help me?

thanks

Francesco

**Comment by floswald** [comment]
Hi please post the full code and output you get followed by `sessionInfo()`
thanks

**Comment by hyperfra** [comment]
Hi 
sorry for late reply. After a few attempts...I managed to create the panel using method 1.  I create my own lists of variables into txt files, had hem, cast them and that works.

The second method, which was the first route I took as more convenient at first sight gives me the error. 

To illustrate this point I just use one of your examples. Below I attach the console output

F

library(psidR)
library(data.table)
# this works
r = system.file(package="psidR")
f = fread("/Users/francescofranco/Dropbox/temp3/fam-vars.txt")
i = fread("/Users/francescofranco/Dropbox/temp3/ind-list.txt")
i = dcast(i[,list(year,name,variable)],year~name, value.var = "variable")
f = dcast(f[,list(year,name,variable)],year~name, value.var = "variable")
d = build.panel(datadir="/Users/francescofranco/Dropbox/temp3",fam.vars=f,ind.vars=i, heads.only = TRUE,sample="SRC",design="all")
write.csv(d,"/Users/francescofranco/Dropbox/temp3/prova_psid.csv")

#this does not works
cwf = openxlsx::read.xlsx(system.file(package="psidR","psid-lists","psid.xlsx"))
head_age_var_name <- getNamesPSID("ER17013", cwf, years=c(2003))
educ = getNamesPSID("ER30323",cwf,years=2003)
famvars = data.frame(year=c(2003),age=head_age_var_name)
indvars = data.frame(year=c(2003),educ=educ)
build.panel(fam.vars=famvars,ind.vars=indvars,datadir="/Users/francescofranco/Dropbox/temp3")
sessionInfo()


[R Console.txt](https://github.com/floswald/psidR/files/4741746/R.Console.txt)
