### ISSUE TITLE
`famvars` allows NA but `indvars` does not

### ISSUE THREAD

**Issue by ntrlshrp** [floswald/psidR#4]
`famvars` allows NA but `indvars` does not. This makes it difficult to build a panel including incomplete individual variables.

    Error in `[.data.table`(ind, , c(def.subsetter, unique(c(ind.subsetter,  : 
      column(s) not found: NA

A workaround may be to assign an unused variable, then set d$data$<unusedvar> to NA?

Example of error:

    ## NA in indvars fails
    ##############################
    famvars = data.frame(year= c( 1968:1969),
                                       fam.head.race= c("V181", "V801") )
    indvars = data.frame(year= c( 1968:1969),
                                      age= c("ER30004", "ER30023"),
                                      sex= c("ER32000"),
                                      grades.completed= c("ER30010", NA) )
    # also non-heads
    d <- build.panel(datadir=mydir,
                 fam.vars=famvars,
                 ind.vars=indvars,
                 heads.only=FALSE,
                 design="all")

    ## NA in famvars succeeds
    ##############################
    famvars = data.frame(year= c( 1968:1969),
                                       fam.head.race= c("V181", NA) )
    indvars = data.frame(year= c( 1968:1969),
                                      age= c("ER30004", "ER30023"),
                                      sex= c("ER32000") )
    # also non-heads
    d <- build.panel(datadir=mydir,
                 fam.vars=famvars,
                 ind.vars=indvars,
                 heads.only=FALSE,
                 design="all")

**Comment by floswald** [comment]
Sounds like a good idea! Can you submit a PR? I don't have time right now
but could do later.

**Comment by floswald** [comment]
left a comment. this is not a bug but an unsupported feature.

**Comment by nilshg** [comment]
Adding to this, it seems to me that the problem is a bit more fundamental when trying to work with 1968 PSID data: 

The individual sequence number in 1968 is hardcoded as `NA` [here](https://github.com/floswald/psidR/blob/master/R/makeids.r#L19), so any attempt to build a panel using 1968 data will fail due to the `NA` being included in `ind.subsetter` (including the example by @ntrlshrp above, ironically).

Not exactly sure what the best workaround is yet, but I'll try to think about it.

**Comment by jonlatner** [comment]
is there any progress on this issue?  for what its worth, the sequence number in 1968 could simply be the same as the relationship to the head in 1968.  however, i tried replacing the NA in the 1968 individual sequence to the relationship to the head and got the following error:

Error in setnames(yind, c("ID1968", "pernum", "interview", "sequence",  : 
  Can't assign 6 names to a 5 column data.table

**Comment by floswald** [comment]
no progress here. I did not foresee the possibility that there might be missing values in the individual variables. I only thought of using the individual index file to perform the merge, take all the actual data from the family file. so this issue would never arise. As I said above, allowing for this needs a completely different strategy. Shouldn't be too hard to do, but it's not top of my list right now. Pull requests more than welcome!

**Comment by jonlatner** [comment]
Florian,

well, i am a total R newbie, so i don't know how useful i can be, but i am
attaching what i did.  its very crude, but perhaps it might give you some
idea of how to proceed.  i still don't have a solution to the 1968 issue
yet...

thanks for putting this together!

JPL

On Tue, Feb 16, 2016 at 10:24 PM, Florian Oswald <notifications@github.com>
wrote:

> no progress here. I did not foresee the possibility that there might be
> missing values in the individual variables. I only thought of using the
> individual index file to perform the merge, take all the actual data from
> the family file. so this issue would never arise. As I said above, allowing
> for this needs a completely different strategy. Shouldn't be too hard to
> do, but it's not top of my list right now. Pull requests more than welcome!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/floswald/psidR/issues/4#issuecomment-184880586>.
>



-- 
Jonathan P. Latner

email: jonlatner@gmail.com
German phone: +49(0) 151 407 98067

**Comment by floswald** [comment]
hi @jonlatner ,
you can't attach stuff here. you can fork this repo, commit your changes and submit as a pull request and I can look at them (most preferred option), or you can just paste the parts of the code you changed in here (click below on "see this on github"). you can make code look nice by using three backticks ``` before and after a code block

```R
x <- 3
```

**Comment by floswald** [comment]
done via 48cc4c3

if you could do some testing would be good, I am ready to update this on CRAN if all runs.
