### ISSUE TITLE
Pre-2007 wealth variables cannot be imported

### ISSUE THREAD

**Issue by leima0521** [floswald/psidR#46]
Hello,

Thank you for building this great package! I got an error when trying to download variables in the wealth supplement

```
Error in `[.data.table`(tmp, , codes[-na], with = FALSE) : 
  column(s) not found: s117, s107, s120
In addition: There were 16 warnings (use warnings() to see them)
```

Here is my code
```
panel_years <- c(seq(1968, 1997, 1), seq(1999, 2017, 2))
cwf <- openxlsx::read.xlsx(system.file(package = "psidR", "psid-lists", "psid.xlsx"))
varlist <- data.frame(
  year = panel_years,
  net_wealth = getNamesPSID("S717", cwf, panel_years),
  nonmort_debt = getNamesPSID("S207", cwf, panel_years),
  home_equity = getNamesPSID("ER46966", cwf, panel_years)
)
```

It returns the errors above. However, if I only use the years after 2009, I can get these variables without a problem. One thing I notice is that the naming conventions are different between the pre-2007 ("Sxxx") and post-2009 ("ERxxxxx") periods. Do you have any suggestions to fix this?

year | home_equity | net_wealth
 -- | -- | --
2003 | S620 | S617
2005 | S720 | S717
2007 | S820 | S817
2009 | ER46966 | ER46970
2011 | ER52390 | ER52394
2013 | ER58207 | ER58211

**Comment by floswald** [comment]
wealth is now shipped with the main family file. no longer supporing keyword `wealth`
