### ISSUE TITLE
issue regarding install_github

### ISSUE THREAD

**Issue by Amrkuls** [floswald/psidR#55]
install_github("psidR",username="floswald")
Error in install_github("psidR", username = "floswald") : 
  could not find function "install_github"

how to address this error

**Comment by floswald** [comment]
This is not a function related to this package. I advise you to

1. Google it
2. Change your tone (please?) or you risk not receiving any further replies from the maintainer of this repo, who is using his spare time so that people like yourself can use it.

Have a good day.

**Comment by Amrkuls** [comment]
Thankyou sir for your immediate replies. I highly apologise for the tone. Thankyou so much for creating this package.
