### ISSUE TITLE
issue regarding function flog.threshold

### ISSUE THREAD

**Issue by Amrkuls** [floswald/psidR#56]
Respected Sir 
I came across the following error. Kindly guide me how to resolve it.The error is as follows:

d = build.panel(datadir=datadr,fam.vars=f,ind.vars=i, heads.only = TRUE,sample="SRC",design="all")
Error in flog.threshold(loglevel) : 
  could not find function "flog.threshold"

Kindly guide me how to address this issue.

**Comment by Greenhand2020miami** [comment]
It is from a package, you may need to install.package("futile.logger")
