### ISSUE TITLE
Question about 2019 and 2021 Family files

### ISSUE THREAD

**Issue by nmaggiulli** [floswald/psidR#60]
Hello,

I was able to download the 2019 Individual data and all the family files through 2017, but I don't see a way to download the 2019 or 2021 files. Is there a simple fix to get these down, or do I need to download them (and import them) manually like I did for the Wealth Supplement files from 1984-2007?

Any feedback would be appreciated.

**Comment by floswald** [comment]
hi there, it seems this update https://github.com/floswald/psidR/pull/57 added the most recent file versions to download. can you post the code you are using here please?

**Comment by nmaggiulli** [comment]
My bad. I had only downloaded the the psidR package from CRAN and not the most recent one here in this repo. For the record, I found that this code is what works for me for getting the package from Github:

install_github("floswald/psidR")

The following code causes an error: install_github("psidR",username="floswald")

Thanks again. I love this package.

**Comment by nmaggiulli** [comment]
Okay, so after downloading the new package I do get the individual file for 2021 but it doesn't download the 2019 or 2021 family files. My guess is that it's because the most recent merge pull request which is supposed to fix this failed. I am not an expert here, but that's my gut reaction. See attached photo of that merge request failing (as it states on the repo).
<img width="529" alt="Screenshot 2024-05-29 at 8 07 25 AM" src="https://github.com/floswald/psidR/assets/13772240/175c197b-47a8-4136-8731-59a51edff78c">

**Comment by floswald** [comment]
Just found a bug. Will push an update later today. In practice your
dataframe specifying variables needs to look like the first example on the
readme. The example which uses the crosswalk file is currently broken

**Comment by floswald** [comment]
fixed now . please reinstall from github

**Comment by floswald** [comment]
package is now updated on CRAN.
