### ISSUE TITLE
Wrong core sample selection?

### ISSUE THREAD

**Issue by nilshg** [floswald/psidR#8]
Either I'm misunderstanding the PSID documentation, or there's a mistake in how the core sample is selected. Check out [line 341](https://github.com/floswald/psidR/blob/master/R/build.panel.r#L341):
````
yind <- copy(yind[ER30001>2930])	# individuals 1-2930 are from poor sample
````
This drops all individuals with a 1968 family interview number 1-2929. But, from the [PSID FAQs](https://psidonline.isr.umich.edu/Guide/FAQ.aspx?Type=ALL#14):

>   How can I identify the SEO (Survey of Economic Opportunity) sample and the SRC (Survey Research Center) sample?

>You will need to look at the 1968 family interview number available in the individual-level files (V30001 and ER30001 in 2007).
>SRC sample families have values less than 3000.
>SEO sample families have values greater than 5000 and less than 7000.

This is also consistent with a dataset from a paper I'm currently replicating, which uses families 1-2930 as the core.

So shouldn't the line read:
````
yind <- copy(yind[ER30001<=2930])	# individuals 1-2930 are from poor sample
````

**Comment by floswald** [comment]
Looks like a bug. Is that so in all years? Can you send the link to that
faq please? Thanks

**Comment by nilshg** [comment]
Sorry, copy-paste failed above, link to FAQs now fixed.
Yes, I believe this is the case in all years - this line is inside the year-loop, so you're selecting the SEO rather than the core sample every year.

**Comment by floswald** [comment]
ok i fixed that. i never used this functionality (always used both samples), but really should have tested this better. I do apologize. I'll also add the other selection criteria later on (latino, etc).

**Comment by floswald** [comment]
i changed the `core` argument to `sample` in a6296960c9f45075bab73baaf6b126a986eb028d, which takes a string now. Testing is greatly improved. thanks again for looking at the code!

**Comment by nilshg** [comment]
That's great, thanks! Are these changes pushed to CRAN as well? I'm having trouble installing RTools on my work machine without admin privileges, so it would be great to be able to downloaded the fixed version from there.

**Comment by floswald** [comment]
Windows binary built now good to go.
